extends:
  - stylelint-config-standard-scss
  - ../.stylelintrc.yml

plugins:
  - stylelint-scss

rules:
  media-query-no-invalid: null
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - use
