const PROGRESS_MIN = 0;
const PROGRESS_MAX = 100;
const NUMBER_OF_ACHIEVEMENTS_TO_DISPLAY = 3;

export { NUMBER_OF_ACHIEVEMENTS_TO_DISPLAY, PROGRESS_MAX, PROGRESS_MIN };
export { SUPPORTED_FILE_TYPES_STRING } from '~/libs/constants/constants.js';
