import { COMMA_SPACE_DELIMITER, SUPPORTED_FILE_TYPES } from './constants.js';

const SUPPORTED_FILE_TYPES_STRING = SUPPORTED_FILE_TYPES.join(
  COMMA_SPACE_DELIMITER,
);

export { SUPPORTED_FILE_TYPES_STRING };
