import {
  addArticle,
  addComment,
  addReactionToArticlesFeed,
  addReactionToArticleView,
  copySharedLink,
  createArticle,
  createComment,
  deleteArticle,
  deleteArticleReaction,
  dropArticleFormDataFromLocalStorage,
  fetchAll,
  fetchAllCommentsToArticle,
  fetchOwn,
  fetchSharedArticle,
  getAllGenres,
  getArticle,
  getArticleIdByToken,
  getImprovementSuggestions,
  getImprovementSuggestionsBySession,
  getSharedLink,
  reactToArticle,
  saveArticleFormDataToLocalStorage,
  setArticleFormDataFromLocalStorage,
  setShowFavourites,
  toggleIsFavourite,
  updateArticle,
  updateArticleAuthorFollowInfo,
  updateComment,
} from './actions.js';
import { actions } from './articles.slice.js';

const allActions = {
  ...actions,
  fetchAll,
  fetchOwn,
  addReactionToArticleView,
  createArticle,
  addComment,
  updateArticle,
  getArticle,
  getAllGenres,
  fetchAllCommentsToArticle,
  createComment,
  updateComment,
  deleteArticle,
  reactToArticle,
  deleteArticleReaction,
  fetchSharedArticle,
  toggleIsFavourite,
  setShowFavourites,
  getImprovementSuggestions,
  getImprovementSuggestionsBySession,
  addArticle,
  addReactionToArticlesFeed,
  updateArticleAuthorFollowInfo,
  getArticleIdByToken,
  getSharedLink,
  copySharedLink,
  dropArticleFormDataFromLocalStorage,
  saveArticleFormDataToLocalStorage,
  setArticleFormDataFromLocalStorage,
};

export { allActions as actions };
export { reducer } from './articles.slice.js';
