import {
  addArticle,
  addComment,
  addReactionToArticlesFeed,
  addReactionToArticleView,
  createArticle,
  createComment,
  deleteArticle,
  deleteArticleReaction,
  fetchAll,
  fetchAllCommentsToArticle,
  fetchOwn,
  fetchSharedArticle,
  geArticleIdByToken,
  getAllGenres,
  getArticle,
  getImprovementSuggestions,
  getImprovementSuggestionsBySession,
  reactToArticle,
  setShowFavourites,
  shareArticle,
  toggleIsFavourite,
  updateArticle,
  updateArticleAuthorFollowInfo,
  updateComment,
} from './actions.js';
import { actions } from './articles.slice.js';

const allActions = {
  ...actions,
  fetchAll,
  fetchOwn,
  addReactionToArticleView,
  createArticle,
  addComment,
  updateArticle,
  getArticle,
  getAllGenres,
  fetchAllCommentsToArticle,
  createComment,
  updateComment,
  deleteArticle,
  reactToArticle,
  deleteArticleReaction,
  shareArticle,
  fetchSharedArticle,
  toggleIsFavourite,
  setShowFavourites,
  getImprovementSuggestions,
  getImprovementSuggestionsBySession,
  addArticle,
  addReactionToArticlesFeed,
  updateArticleAuthorFollowInfo,
  geArticleIdByToken,
};

export { allActions as actions };
export { reducer } from './articles.slice.js';
